### ISSUE TITLE
.eslintignore not honoured

### ISSUE THREAD

**Issue by martiensk** [glat/MultiLinter#4]
It looks like the .eslintignore file is not honoured. It works if I lint from my project root directory, which is also the directory my .eslintrc and .eslintignore files are located in.

Here is the directory structure: 
<pre>
| Project Root
| -- .eslintrc
| -- .multilinterrc
| -- .eslintignore
| -> node_modules
     | -> .bin
          | -- eslint.cmd
</pre>

This is the content of my .eslintignore:

<pre>
/node_modules
/Content
/packages
/Scripts
</pre>

The file that I am trying to ignore with the linter is located in the "Content" folder.
This is the result when linting via the terminal:
![image](https://user-images.githubusercontent.com/19816791/68464266-3c20d500-0208-11ea-903b-b564c92f0b8f.png)

However, if I navigate to the same file in Visual Studio it is definitely linted. This is from the multilinter debug console:

![image](https://user-images.githubusercontent.com/19816791/68464005-aab16300-0207-11ea-84d1-3aedbd9f36e4.png)

I have also tried different glob patterns in the .eslintignore, including:
<pre>
/Content/*
/Content/**/*
/Content/**/*.js
</pre>

**Comment by glat** [comment]
I confirm the behaviour. It seems that current directory should be set to the project directory when launching linter. In last release it is set to the file directory and linter does not understand that it's in a directory to ignore to.

Fix will come. I'll let you know.

Keep in mind that you've to set "On Save" linting, otherwise the shadow copy created is located in %TEMP% and so no ignore will be honoured.

**Comment by glat** [comment]
Fix is live on extensions store. Please upgrade and check it.

I changed "Real Time" linting. Now shadow file is temporarily saved in same directory of file with a temporary filename (<filename><dot><random chars><dot><extension>) and deleted after linting.
In folder projects it can appear for a moment in VS project explorer.

Let me know

**Comment by martiensk** [comment]
Looks good mate. Thank you very much, I will happily close this issue.
