### ISSUE TITLE
Where is the source code?

### ISSUE THREAD

**Issue by Indigo744** [glat/MultiLinter#5]
Hello,

I was surprised to only find a readme and an example config in this repository.

Is there any reason for that?

Thanks.

**Comment by glat** [comment]
Ask to @jwldnr

**Comment by Indigo744** [comment]
I'm sorry but I fail to understand. Care to elaborate a bit?

Is this extension tied to https://github.com/jwldnr/VisualLinter in some way?

**Comment by jwldnr** [comment]
> Ask to @jwldnr

@glat I understand that this extension is a fork of https://github.com/jwldnr/VisualLinter then?

**Comment by glat** [comment]
I can't state publicy what I think. So, please stop, asking about this point.
NO, it's a complete rewrite.

**Comment by jwldnr** [comment]
Since my extension is now retired; I have no problem with you using my extension as inspiration or even using parts of the code in this project. @glat

**Comment by glat** [comment]
Perhaps you've no problem, but I've a lot of them. This is not an issue so, again, please stop.

**Comment by Indigo744** [comment]
> I can't state publicy what I think. So, please stop asking about this point.
... What? Why!? What's the issue with talking about open source code?

And even if you forked the VisualLinter extension, it is absolutely not a problem since the extension is actually licensed under MIT.

I really don't understand what is the problem.
